version: '2'
services:
  minio:
    image: shareai/minio:x86
    restart: always
    container_name: "minio"
    ports:
      - 9000:9000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  broker:
    image: shareai/broker:x86
    restart: always
    container_name: "broker"
    ports:
      - 1883:1883
      - 9001:9001
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  api_server:
    container_name: "api_server"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    image: shareai/api_server:latest
    ports:
      - 3000:3000
    restart: always
