version: '2'
services:
  redis:
    image: shareai/redis:arm32v7
    build:
      context: ./redis
      dockerfile: Dockerfile
  broker:
    image: shareai/broker:arm32v7
    build:
      dockerfile: Dockerfile
      context: ./broker
  flower:
    image: shareai/flower:arm32v7
    build:
      context: ./flower
  camera:
    image: shareai/shinobi:arm32v7
    build:
      context: ../src/camera
  face_detector:
    image: shareai/face_detector:arm32v7
    build:
      context: ../src/face_detection
      dockerfile: Dockerfile
  embedding:
    image: shareai/embedding:v1.1_arm32v7
    build:
      context: ../src/embedding
  rtspserver:
    image: shareai/rtspserver:arm32v7
    build:
      context: ./v4l2rtspserver
