version: '2'
services:
  redis:
    image: shareai/redis:x86
    build:
      context: ./redis
      dockerfile: Dockerfile.x86
  flower:
    image: shareai/flower:x86
    build:
      context: ./flower
      dockerfile: Dockerfile.x86
  broker:
    image: shareai/broker:x86
    build:
      dockerfile: Dockerfile.x86
      context: ./broker
  camera:
    image: shareai/nvr:x86
    build:
      context: ../src/camera
      dockerfile: Dockerfile.x86
  face_detector:
    image: shareai/face_detector:x86
    build:
      context: ../src/face_detection
      dockerfile: Dockerfile.x86
  embedding:
    image: shareai/embedding:x86
    build:
      context: ../src/embedding
      dockerfile: Dockerfile.x86
