#!/bin/bash

export DEVICE_UUID_FILEPATH=/data/data/com.termux/files/home/.ro_serialno
export DEVICE_GROUP_ID_FILEPATH=/data/data/com.termux/files/home/.groupid.txt

while [ 1 ]
do
  ONE_KNOWN_PERSON_BYPASS_QUEUE_MODE=0 DEEP_ANALYSIS_MODE=1 SAMPLING_TO_SAVE_ENERGY_MODE=0 RESTRICT_RECOGNITON_MODE=0 MINIMAL_FACE_RESOLUTION=100 BIGGEST_FACE_ONLY_MODE=0 UPLOAD_IMAGE_SERVICE_ENABLED=0 GIF_UPLOADING=1 REALTIME_STRANGER_SDK_MESSAGE=1 ENABLE_STATIC_OBJECT_FILTER=true CLUSTER_REDIS_ADDRESS=localhost CLUSTER_REDIS_PORT=6379 CLUSTER_CONCURRENCY=80  REDIS_HOST=localhost FLOWER_ADDRESS=localhost FLOWER_PORT=5556 BROKERHOST='mqtt://localhost' node index.js
  sleep 20
done
